### ISSUE TITLE
The splitlock detector does not work on Windows

### ISSUE THREAD

**Issue by thiagomacieira** [opendcdiag/opendcdiag#313]
The implementation in https://github.com/opendcdiag/opendcdiag/blob/d7d457f2d4283fbf0bd5c46c79d9eed729480fb5/framework/sysdeps/windows/splitlock_detect.c#L13-L44 does not work because it'll always resume at the crashing instruction.

This has probably never been tested. I don't even know if Windows has the ability to turn the split lock detection into enforcement.

This code probably parallels the original implementation of the Unix version of the split lock detector, which used a signal handler and `siglongjmp`. I don't remember why that didn't work, but I do remember that at some point I caused it to resume the same crashing instruction and thus go into an infinite loop of crash-and-resume.

**Comment by jarodrig** [comment]
Windows won't throw split lock exceptions.

**Comment by thiagomacieira** [comment]
Thanks, so I'm closing this for now as "Won't fix".
