### ISSUE TITLE
Framework restarts the test after a signal is received

### ISSUE THREAD

**Issue by thiagomacieira** [opendcdiag/opendcdiag#429]
This a regression since b7dbacbdb2c509a26ced509dad93389003d1f974 or thereabouts.

### Test
```sh
./opendcdiag --selftests -e selftest_timedpass_busywait -o - & 
sleep 0.1
kill -INT %+
wait
```

### Expected behaviour
OpenDCDiag exits immediately, reports "exit: interrupted" and re-raises the signal that interrupted it.
```
tests:
- test: selftest_freeze
  details: { quality: beta, description: "Freezes" }
  state: { seed: 'AES:8935d753c2767a50eed11b84ca99b5f376ca28ac3d8985af112ee47b35664a0c', iteration: 0, retry: false }
  time-at-start: { elapsed:      0.000, now: !!timestamp '2023-10-12T23:59:13Z' }
# Caught SIGINT, stopping current test (press Ctrl+C again to exit without waiting)                                                                              
  result: interrupted
  fail: { cpu-mask: null, time-to-fail: null, seed: 'AES:8935d753c2767a50eed11b84ca99b5f376ca28ac3d8985af112ee47b35664a0c'}
  time-at-end:   { elapsed:     97.999, now: !!timestamp '2023-10-12T23:59:13Z' }
  test-runtime: 97.508
exit: interrupted
[2]  + interrupt  ./opendcdiag --selftests -e selftest_freeze -Y -o -
```

### Actual behaviour
The current test is terminated but it is restarted again, for retesting, leading to "exit: fail" and exit code 1 instead.
```
$ ./opendcdiag --selftests -e selftest_timedpass_busywait -o - --retest-on-failure=1 & sleep 0.1; kill -INT %+; fg
...
tests:
- test: selftest_timedpass_busywait
  details: { quality: beta, description: "Runs for the requested time, but busy-waiting" }
  state: { seed: 'AES:5a1081f8f55be6ea4cab76a4f271e845a5ef7e070aa41915b354895b0d8e17ba', iteration: 0, retry: false }
  time-at-start: { elapsed:      0.000, now: !!timestamp '2023-10-12T23:58:01Z' }
[1]  + 3638813 running    ./opendcdiag --selftests -e selftest_timedpass_busywait -o - 
# Caught SIGINT, stopping current test (press Ctrl+C again to exit without waiting)
  result: crash
  result-details: { crashed: true, core-dump: false, code: 2, reason: 'Interrupt' }
  fail: { cpu-mask: null, time-to-fail: null, seed: 'AES:5a1081f8f55be6ea4cab76a4f271e845a5ef7e070aa41915b354895b0d8e17ba'}
  time-at-end:   { elapsed:     83.333, now: !!timestamp '2023-10-12T23:58:01Z' }
  test-runtime: 80.739
- test: selftest_timedpass_busywait
  details: { quality: beta, description: "Runs for the requested time, but busy-waiting" }
  state: { seed: 'AES:5a1081f8f55be6ea4cab76a4f271e845a5ef7e070aa41915b354895b0d8e17ba', iteration: 1, retry: true }
  time-at-start: { elapsed:     83.333, now: !!timestamp '2023-10-12T23:58:01Z' }
  result: pass
  time-at-end:   { elapsed:    283.333, now: !!timestamp '2023-10-12T23:58:01Z' }
  test-runtime: 200.283
- test: selftest_timedpass_busywait
  details: { quality: beta, description: "Runs for the requested time, but busy-waiting" }
  state: { seed: 'AES:5a1081f8f55be6ea4cab76a4f271e845a5ef7e070aa41915b354895b0d8e17ba', iteration: 2, retry: true }
  time-at-start: { elapsed:    283.333, now: !!timestamp '2023-10-12T23:58:01Z' }
  result: pass
  time-at-end:   { elapsed:    483.334, now: !!timestamp '2023-10-12T23:58:01Z' }
  test-runtime: 200.275
# Test failed 1 out of 3 times (33.3%)
# Topology analysis:
# Loop iteration 1 finished, average time 481.528 ms, total 481.528 ms
triage-results: [ 0 ]
exit: fail
```

**Comment by jposwiata** [comment]
It seems that this covers several "other" issues related to signal handling:
1. SIGTERM should stop the application (immediately). Currently doesn't break at all.
2. first SIGINT should stop current running test (log "press CtrlC second time"), at the end application should report "Interrupted" (or any "higher" failure if found). Currently the app reports failure at the end, and the tests run "from scratch" without configuration data (with --max-test-loop-count = **-1**)
3. Second SIGINT should kill the application with "Interrupted".

**Comment by jposwiata** [comment]
Is "two phase SIGINT" feature valid?  Should `# Caught SIGINT, stopping current test (press Ctrl+C again to exit without waiting)` be emitted by the app?

**Comment by oxavelar-intel** [comment]
> The current test is terminated but it is restarted again, for retesting, leading to "exit: fail" and exit code 1 instead.

That is exactly what our team is also observing, thanks for the follow-up. Under `SIGTERM` in our tests where we would expect graceful handling to stop gracefuly are not stopping and eventually getting into `exit: fail` and exit code of 1.

**Comment by thiagomacieira** [comment]
The signal handler exists to ensure the tool writes the log before exiting, so you don't have a truncated output. The special case for SIGINT is there to wait for the child process(es) to exit cleanly too.

This bug must have been introduced by 37cb3e5404eea2847c5da5fe576be0268282b8ee, which added support for multiple children.
