### ISSUE TITLE
Consider not stopping OpenDCDiag if non-existing test is used in `-e` option

### ISSUE THREAD

**Issue by dawid-sabat** [opendcdiag/opendcdiag#490]
We can consider to handle this behavior differently. Right now if we mix `-e` option with non-existing test name among other existing tests, this will break OpenDCDiag run.

What if we print a warning `Cannot find test 'no-test-here'` but continue with other valid entries?

**Comment by thiagomacieira** [comment]
That's `--ignore-unknown-tests`, isn't it?

**Comment by dawid-sabat** [comment]
Yes, looks like this option hasn't shown on my radar. It's doing precisely what I needed. Closing.
