### ISSUE TITLE
Use `native` files to reduce hard-coding (arbitrary) options

### ISSUE THREAD

**Issue by thac0** [opendcdiag/opendcdiag#54]
Meson supports `native` configurations, which are analogous to CMake presets. We could have one per desired buildtype, where we could set built-in values-- e.g. `optimization` level, `[C,CPP]FLAGS`.

This could reduce the number of manually-appended flags in our `.build` files.

**Comment by thiagomacieira** [comment]
I don't think we can do that from the `meson.build` files, so it would be up to the user to choose to use the options, right? If so, I don't think this is a good idea.

**Comment by thac0** [comment]
It would be up to the user to specify which `native` file to use-- those files would house preset flags, settings, options, etc.

**Comment by thac0** [comment]
Suggestion died on the vine. Closing.
